export const INIT_DATA = 'INIT_DATA';
export const SHOW_ERROR_POPUP = 'SHOW_ERROR_POPUP';
export const SHOW_SUCCESS_POPUP = 'SHOW_SUCCESS_POPUP';
export const CLOSE_ERROR_POPUP = 'CLOSE_ERROR_POPUP';
export const CLOSE_SUCCESS_POPUP = 'CLOSE_SUCCESS_POPUP';
